### ISSUE TITLE
support for Oracle Container Cloud Service

### ISSUE THREAD

**Issue by yakirlevi** [oracle/oci-dotnet-sdk#115]
Hey.
I wondered if there is a plan to add support for the Container Service? we are using this library and currently this is the one thing missing for us.

Thanks.

**Comment by github-anurag** [comment]
Hi @yakirlevi 
The Dotnet SDK supports most of the publicly available OCI APIs. The APIs documentation can be found at: https://docs.oracle.com/en-us/iaas/api/ 

If the API/Service you are looking for is present in this list then the Dotnet SDK should most probably support it as well.

If the API/Service is not present in this list then can you please elaborate more on the Service you want to use so that we may forward your request to the correct team.

**Comment by jodoglevy** [comment]
@yakirlevi which service do you mean by "Container service"? Can you point us to a documentation link about it so we're clear on which service you're talking about?

If you mean [OKE](https://www.oracle.com/cloud-native/container-engine-kubernetes/), the SDK already supports this service.

**Comment by yakirlevi** [comment]
Hey. 
It's not the OKE service.  Here is the docs on this service: https://docs.oracle.com/en/cloud/iaas-classic/container-cloud/contu/administering-oracle-container-cloud-service.html#GUID-5E984CAA-C1C0-4427-80E6-C0D3EDD3629F
And API:  https://docs.oracle.com/en/cloud/iaas-classic/container-cloud/conta/rest-endpoints.html
