### ISSUE TITLE
.net Sdk packages publisher and tagging on Nuget.org

### ISSUE THREAD

**Issue by dumians** [oracle/oci-dotnet-sdk#8]
Dear All,
Just small point , on Nuget.org oci-dotnet-sdk packages  are not listed on query filter Oracle -> https://www.nuget.org/packages?q=oracle as well on searching for Cloud , oracle cloud tags and Publisher Profile it's not official Oracle.

Impact -> Developers searching in their IDE interface from the Nuget Feed , will not find them easy.

Best ,
Johannes

**Comment by buzhidao77** [comment]
Thanks for the feedback. We'll add appropriate tags.

**Comment by viralmodi** [comment]
@dumians Thanks for your feedback. We have the following tags on our packages currently: "Oracle", "OCI", "Cloud", "ocisdk" and "OracleCloudInfrastructure". Since our product is newly launched, searching with some of these keywords finds the packages but puts them behind in search ranking. If you browse by clicking "Next", you will find our packages listed. Searching with "Oracle Cloud .NET SDK" currently can get our packages on second page.
 
FYI, Oracle Cloud is popularized as OCI for short in our cloud public docs. If you search for OCI on nuget.org, you will find our packages.

We are working to get "Oracle" owner profile added to our packages as well.

Regarding your comment on Publisher profile being "official Oracle", I don't think Nuget provides a way to verify whether someone claiming "Oracle" as the Publisher name are official Oracle or not.

**Comment by viralmodi** [comment]
1) I was able to get "Oracle" added as owner to our packages in nuget.org. 
2) We also updated our tags to help with discoverability. Searching for "OracleCloud" on nuget now shows our packages first. Searching for Oracle still doesn't show our packages on the first page since Oracle tag is used by several other packages and I think the packages are shown based on their downloads/popularity.
We have achieved our goal of achieving better discoverability and better trustworthiness on nuget.org by doing the above 2 steps. I will close the ticket with this comment.
